"use client";
import { useEffect, useState } from "react";

const EVENT_NAME=process.env.NEXT_PUBLIC_EVENT_NAME||"Amigo Invisible TMF";
const EVENT_DATE=process.env.NEXT_PUBLIC_EVENT_DATE||"2026-07-23";
const GIFT_BUDGET=process.env.NEXT_PUBLIC_GIFT_BUDGET||"$20000";
const clueCalendar=["Pista 1 - Martes 7/7","Pista 2 - Jueves 9/7","Pista 3 - Martes 14/7","Pista 4 - Jueves 16/7","Pista 5 - Martes 21/7","Pista final - Miércoles 22/7"];
function daysLeft(){const d=new Date(`${EVENT_DATE}T00:00:00`).getTime()-new Date().getTime();return Math.max(0,Math.ceil(d/(1000*60*60*24)))}

export default function Home(){
 const [code,setCode]=useState(""),[savedCode,setSavedCode]=useState(""),[participant,setParticipant]=useState(null),[clues,setClues]=useState([]),[clueText,setClueText]=useState(""),[selectedClue,setSelectedClue]=useState(clueCalendar[0]),[revealed,setRevealed]=useState(false),[loading,setLoading]=useState(false),[msg,setMsg]=useState("");
 async function loadData(activeCode){setLoading(true);setMsg("");try{const res=await fetch("/api/me",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:activeCode})});const data=await res.json();if(!res.ok)throw new Error(data.error||"No se pudo ingresar.");setParticipant(data.participant);setClues(data.clues||[]);setSavedCode(activeCode);localStorage.setItem("amigoCode",activeCode)}catch(e){setMsg(e.message);localStorage.removeItem("amigoCode")}finally{setLoading(false)}}
 async function login(e){e.preventDefault();const clean=code.trim().toUpperCase();if(clean)await loadData(clean)}
 async function sendClue(e){e.preventDefault();setLoading(true);setMsg("");try{const res=await fetch("/api/clues",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:savedCode,text:clueText,type:selectedClue})});const data=await res.json();if(!res.ok)throw new Error(data.error||"No se pudo enviar la pista.");setClueText("");setMsg("Pista enviada correctamente.");await loadData(savedCode)}catch(e){setMsg(e.message)}finally{setLoading(false)}}
 function logout(){localStorage.removeItem("amigoCode");setParticipant(null);setClues([]);setSavedCode("");setCode("");setRevealed(false);setMsg("")}
 useEffect(()=>{const existing=localStorage.getItem("amigoCode");if(existing)loadData(existing)},[]);
 if(!participant)return <main><div className="card small-card"><div className="logo">🎁</div><h1>{EVENT_NAME}</h1><p className="muted">Ingresá tu código secreto para ver a quién te tocó y usar tu buzón digital.</p><form onSubmit={login} className="grid"><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Código secreto" autoFocus/><button disabled={loading}>{loading?"Ingresando...":"Ingresar"}</button></form>{msg&&<p className="error">{msg}</p>}</div></main>;
 return <main><div className="card"><div className="row space"><div><div className="logo">🎁</div><h1>{EVENT_NAME}</h1><p className="muted">Hola, {participant.name}. Faltan <b>{daysLeft()}</b> días para el intercambio.</p><span className="badge">Fecha: 23 de julio</span><span className="badge">Presupuesto: {GIFT_BUDGET}</span></div><button className="secondary" onClick={logout}>Salir</button></div><div className="grid two" style={{marginTop:24}}><section className="section"><h2>🎯 Mi amigo invisible</h2>{!revealed?<><p className="muted">Tocá para revelar a quién tenés que hacerle el regalo.</p><button onClick={()=>setRevealed(true)}>Revelar mi amigo</button></>:<><div className="friend">{participant.assignedToName}</div><p className="muted">Guardá el secreto hasta el intercambio.</p></>}</section><section className="section"><h2>📅 Calendario de pistas</h2>{clueCalendar.map(i=><span className="badge" key={i}>{i}</span>)}</section></div><div className="grid two" style={{marginTop:18}}><section className="section"><h2>✉️ Enviar pista</h2><p className="muted">La pista llega al buzón de tu amigo. No muestra quién la envió.</p><form className="grid" onSubmit={sendClue}><select value={selectedClue} onChange={e=>setSelectedClue(e.target.value)}>{clueCalendar.map(i=><option key={i}>{i}</option>)}</select><textarea value={clueText} onChange={e=>setClueText(e.target.value)} placeholder="Escribí una pista divertida, pero que no sea demasiado obvia..." maxLength={300}/><button disabled={loading}>{loading?"Enviando...":"Enviar pista"}</button></form></section><section className="section"><h2>🕵️ Pistas que recibí</h2>{clues.length===0?<p className="muted">Todavía no recibiste pistas.</p>:clues.map((clue,index)=><div className="clue" key={clue.id}><strong>{clue.type||`Pista ${index+1}`}</strong><p>{clue.text}</p></div>)}</section></div>{msg&&<p className={msg.includes("correctamente")?"success":"error"}>{msg}</p>}</div></main>
}
